server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:mem:demo
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp  